name: Enigma2 CI

on: [push, pull_request]

jobs:
  build:
    env:
      CC: "gcc-${{ matrix.gcc }}"
      CXX: "g++-${{ matrix.gcc }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        gcc: [8, 10]
        python: [2.7,3.8]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - name: install gcc ${{ matrix.gcc }}
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -q update
        sudo apt install g++-${{ matrix.gcc }}
    - name: install dev packages
      run: |
        sudo apt-get -q update
        sudo apt-get install \
        linux-libc-dev git build-essential libboost-all-dev \
        automake libtool zlib1g-dev gettext \
        swig libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
        libfreetype6-dev libsigc++-2.0-dev libxml2-dev libfribidi-dev \
        libssl-dev libavahi-client-dev libjpeg-turbo8-dev \
        libgif-dev
    - name: Installing Python 3.8
      if: ${{ matrix.python == '3.8' }}
      run: |
        sudo apt install python3.8-dev python3-pip
        sudo unlink /usr/bin/python
        sudo ln -s /usr/bin/python3.8 /usr/bin/python
        python -m pip install --upgrade pip tox six
        python -V
    - name: Installing Python 2.7
      if: ${{ matrix.python == '2.7' }}
      run: |
        sudo apt install python2.7-dev python-pip
        pip install --upgrade pip tox
        python -V
    - name: Getting gstreamer
      run: |
        python -V 
        cd /tmp/
        curl -L https://people.freedesktop.org/~slomo/gstreamer.tar.gz | tar xz
        sed -i "s;prefix=/root/gstreamer;prefix=$PWD/gstreamer;g" $PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig/*.pc
    - name: Getting libdvbsi++
      run: |
        cd /tmp
        git clone --depth 1 git://git.opendreambox.org/git/obi/libdvbsi++.git
        cd libdvbsi++
        autoreconf -i
        ./configure
        make
        sudo make install
        echo $PATH
    - name: Getting tuxtxt
      run: |
        export PATH=$PATH:/tmp/gstreamer/bin
        export LD_LIBRARY_PATH=/tmp/gstreamer/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
        PKG_CONFIG_PATH=/tmp/gstreamer/lib/x86_64-linux-gnu/pkgconfig
        GST_PLUGIN_SYSTEM_PATH=/tmp/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0
        GST_PLUGIN_SCANNER=/tmp/gstreamer/libexec/gstreamer-1.0/gst-plugin-scanner
        cd /tmp
        git clone --depth 1 https://github.com/OpenPLi/tuxtxt.git
        cd tuxtxt/libtuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
        cd ../tuxtxt
        autoreconf -i
        ./configure --with-boxtype=generic DVB_API_VERSION=5
        make
        sudo make install
    - name: build enigma2
      run: |
        export PATH=$PATH:/tmp/gstreamer/bin
        export LD_LIBRARY_PATH=/tmp/gstreamer/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
        PKG_CONFIG_PATH=/tmp/gstreamer/lib/x86_64-linux-gnu/pkgconfig
        GST_PLUGIN_SYSTEM_PATH=/tmp/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0
        GST_PLUGIN_SCANNER=/tmp/gstreamer/libexec/gstreamer-1.0/gst-plugin-scanner
        autoreconf -i
        ./configure --with-libsdl=no --with-boxtype=nobox --enable-dependency-tracking ac_cv_prog_c_openmp=-fopenmp --with-textlcd --with-gstversion=1.0 
        make
        python -m compileall .
