name: pycodestyle

on:
  push:
    branches: [python3]
  pull_request:
    branches: [python3]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-1

      - name: pycodestyle
        run: |
          pip install pycodestyle
          pycodestyle --config=setup.cfg
